#version 450

#macros

layout(local_size_x=WORK_GROUP, local_size_y=1, local_size_z=1) in;

uniform int p;
uniform int q;

layout(std430, binding = 0) buffer InputBufferA
{
  uint idxs[ ];
};

layout(std430, binding = 1) buffer InputBufferB
{
  float dists[ ];
};

void main( )
{
	uint gid = gl_GlobalInvocationID.x;

	int dist = 1 << ( p - q );

	if( ( gid & dist ) == 0 )
	{
		uint partner = gid | dist;

    bool dir = ( ( gid >> p ) & 2 ) == 0;

		float srcDist = dists[gid];
		float destDist = dists[partner];

		if( srcDist < destDist == dir )
		{
			// Sort positions
			dists[gid] = destDist;
			dists[partner] = srcDist;

      uint tempIdx = idxs[gid];
      idxs[gid] = idxs[partner];
      idxs[partner] = tempIdx;
    }
  }
}