FIND_PACKAGE(PkgConfig)

PKG_CHECK_MODULES(PC_VPX vpx)
FIND_PATH(VPX_INCLUDE_DIR vpx.h
	HINTS ${PC_VPX_INCLUDEDIR} ${PC_VPX_INCLUDE_DIRS}
	NO_DEFAULT_PATH
	)

IF(${VPX_INCLUDE_DIR} STREQUAL VPX_INCLUDE_DIR-NOTFOUND)
	FIND_PATH(VPX_INCLUDE_DIR vpx.h) #try to use default dirs...
ENDIF()

IF(${VPX_INCLUDE_DIR} STREQUAL VPX_INCLUDE_DIR-NOTFOUND)
	FILE(GLOB_RECURSE VPX_INCLUDE_DIR "/vpx*/vpx.h") #last resort! , besides the directory name may be different... it's very bad anyway
	IF(NOT ${VPX_INCLUDE_DIR} STREQUAL VPX_INCLUDE_DIR-NOTFOUND)
		GET_FILENAME_COMPONENT(VPX_INCLUDE_DIR ${VPX_INCLUDE_DIR} PATH)
	ENDIF()
ENDIF()

IF(${VPX_INCLUDE_DIR} STREQUAL VPX_INCLUDE_DIR-NOTFOUND)
	PKG_CHECK_MODULES(PC_VPX libvpx)
	FIND_PATH(VPX_INCLUDE_DIR vpx.h
		HINTS ${PC_VPX_INCLUDEDIR} ${PC_VPX_INCLUDE_DIRS}
		NO_DEFAULT_PATH)
ENDIF()

IF(${VPX_INCLUDE_DIR} STREQUAL VPX_INCLUDE_DIR-NOTFOUND)
	MESSAGE(STATUS "Can't find vpx!")
ELSE()
	MESSAGE(STATUS "Found vpx: ${VPX_INCLUDE_DIR}")

	#GET_FILENAME_COMPONENT(VPX_PARENT ${VPX_INCLUDE_DIR} PATH)
	SET(VPX_PARENT ${VPX_INCLUDE_DIR})
	MESSAGE(STATUS "Using vpx dir parent as hint: ${VPX_PARENT}")

	IF(NOT WIN32)
		FIND_LIBRARY(VPX_LIBRARIES vpx
			HINTS ${PC_VPX_LIBDIR} ${PC_VPX_LIBRARY_DIR} ${VPX_PARENT}
			NO_DEFAULT_PATH)
		IF(${VPX_LIBRARIES} STREQUAL VPX_LIBRARIES-NOTFOUND)
			FIND_LIBRARY(VPX_LIBRARIES libvpx
				HINTS ${PC_VPX_LIBDIR} ${PC_VPX_LIBRARY_DIR} ${VPX_PARENT}
				NO_DEFAULT_PATH)
		ENDIF()
	ELSE()
		FIND_FILE(VPX_LIBRARIES NAMES libvpx.lib HINTS ${VPX_PARENT})
#		SET(VPX_LIBRARIES "${VPX_LIBRARIES}/libvpx.lib")
	ENDIF()

	IF(NOT ${VPX_INCLUDE_DIR} STREQUAL VPX_INCLUDE_DIR-NOTFOUND
		AND NOT ${VPX_LIBRARIES} STREQUAL VPX_LIBRARIES-NOTFOUND)
	
		SET(VPX_FOUND 1)
		SET(VPX_INCLUDE_DIRS ${VPX_INCLUDE_DIR})
		SET(VPX_LIBS ${VPX_LIBRARIES})
	
		MESSAGE(STATUS "vpx include: ${VPX_INCLUDE_DIRS}")
		MESSAGE(STATUS "vpx lib: ${VPX_LIBS}")
	ELSE()
		MESSAGE(STATUS "Can't find vpx")
	ENDIF()
ENDIF()
